version: '3'


volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    container_name: backend
    image: nasty105/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
  frontend:
    container_name: frontend
    image: nasty105/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    container_name: gateway
    image: nasty105/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/media
    ports:
      - 9000:80
