version: '3'


volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: nasty105/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/cats/images/

  frontend:
    container_name: frontend
    image: nasty105/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    container_name: gateway
    image: nasty105/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/media/cats/images
    ports:
      - 9000:80
